// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type addrfilterConfigType uint32

const (
	addrfilterConfigTypeKILL_MODE addrfilterConfigType = 0
	addrfilterConfigTypeCFG_END   addrfilterConfigType = 1
)

type addrfilterKillMode uint32

const (
	addrfilterKillModeKILL_PID      addrfilterKillMode = 0
	addrfilterKillModeKILL_ALL      addrfilterKillMode = 1
	addrfilterKillModeWARN          addrfilterKillMode = 2
	addrfilterKillModeKILL_MODE_END addrfilterKillMode = 3
)

type addrfilterProfileInfo struct {
	Start           uint64
	GetPid          uint64
	ApplyFilter     uint64
	FindSyscallSite uint64
	AssignFilename  uint64
	AssocWhitelist  uint64
	End             uint64
}

type addrfilterStackTraceT struct {
	FramesWalked int32
	_            [4]byte
	Callsite     uint64
	Stacktrace   [32]uint64
}

type addrfilterStatType uint32

const (
	addrfilterStatTypeGET_CUR_TASK_FAILED      addrfilterStatType = 0
	addrfilterStatTypeTP_ENTERED               addrfilterStatType = 1
	addrfilterStatTypeGET_PROFILER_FAILED      addrfilterStatType = 2
	addrfilterStatTypeIGNORE_PID               addrfilterStatType = 3
	addrfilterStatTypePID_READ_FAILED          addrfilterStatType = 4
	addrfilterStatTypePPID_READ_FAILED         addrfilterStatType = 5
	addrfilterStatTypeFOLLOW_FORK_FAILED       addrfilterStatType = 6
	addrfilterStatTypeLIBC_NOT_LOADED          addrfilterStatType = 7
	addrfilterStatTypeSTK_DBG_EMPTY            addrfilterStatType = 8
	addrfilterStatTypeGET_STACK_FAILED         addrfilterStatType = 9
	addrfilterStatTypeCALLSITE_LIBC            addrfilterStatType = 10
	addrfilterStatTypeSTACK_TOO_SHORT          addrfilterStatType = 11
	addrfilterStatTypeNO_RP_MAPPING            addrfilterStatType = 12
	addrfilterStatTypeRP_NULL_AFTER_MAP        addrfilterStatType = 13
	addrfilterStatTypeFILENAME_TOO_LONG        addrfilterStatType = 14
	addrfilterStatTypeFIND_VMA_FAILED          addrfilterStatType = 15
	addrfilterStatTypeNO_VMA_BACKING_FILE      addrfilterStatType = 16
	addrfilterStatTypeWHITELIST_MISSING        addrfilterStatType = 17
	addrfilterStatTypeSYSCALL_BLOCKED          addrfilterStatType = 18
	addrfilterStatTypeSEND_SIGNAL_FAILED       addrfilterStatType = 19
	addrfilterStatTypeKILLMODE_CFG_MISSING     addrfilterStatType = 20
	addrfilterStatTypeWARN_FAILED_RINGBUF_FULL addrfilterStatType = 21
	addrfilterStatTypeSTAT_END                 addrfilterStatType = 22
)

type addrfilterSyscallWhitelist struct{ Bitmap [58]uint8 }

type addrfilterVmRange struct {
	Start    uint64
	End      uint64
	Filename [256]int8
}

// loadAddrfilter returns the embedded CollectionSpec for addrfilter.
func loadAddrfilter() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_AddrfilterBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load addrfilter: %w", err)
	}

	return spec, err
}

// loadAddrfilterObjects loads addrfilter and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*addrfilterObjects
//	*addrfilterPrograms
//	*addrfilterMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadAddrfilterObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadAddrfilter()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// addrfilterSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type addrfilterSpecs struct {
	addrfilterProgramSpecs
	addrfilterMapSpecs
	addrfilterVariableSpecs
}

// addrfilterProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type addrfilterProgramSpecs struct {
	Addrfilter *ebpf.ProgramSpec `ebpf:"addrfilter"`
}

// addrfilterMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type addrfilterMapSpecs struct {
	CfgMap           *ebpf.MapSpec `ebpf:"cfg_map"`
	LibcRangeMap     *ebpf.MapSpec `ebpf:"libc_range_map"`
	PathWhitelistMap *ebpf.MapSpec `ebpf:"path_whitelist_map"`
	ProfileBuf       *ebpf.MapSpec `ebpf:"profile_buf"`
	ProtectMap       *ebpf.MapSpec `ebpf:"protect_map"`
	StackDbgMap      *ebpf.MapSpec `ebpf:"stack_dbg_map"`
	StatsMap         *ebpf.MapSpec `ebpf:"stats_map"`
	WarnBuf          *ebpf.MapSpec `ebpf:"warn_buf"`
}

// addrfilterVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type addrfilterVariableSpecs struct {
	UnusedConfigType       *ebpf.VariableSpec `ebpf:"unused_config_type"`
	UnusedKillMode         *ebpf.VariableSpec `ebpf:"unused_kill_mode"`
	UnusedProfileInfo      *ebpf.VariableSpec `ebpf:"unused_profile_info"`
	UnusedStDbg            *ebpf.VariableSpec `ebpf:"unused_st_dbg"`
	UnusedStatType         *ebpf.VariableSpec `ebpf:"unused_stat_type"`
	UnusedSyscallWhitelist *ebpf.VariableSpec `ebpf:"unused_syscall_whitelist"`
	UnusedVmRange          *ebpf.VariableSpec `ebpf:"unused_vm_range"`
}

// addrfilterObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadAddrfilterObjects or ebpf.CollectionSpec.LoadAndAssign.
type addrfilterObjects struct {
	addrfilterPrograms
	addrfilterMaps
	addrfilterVariables
}

func (o *addrfilterObjects) Close() error {
	return _AddrfilterClose(
		&o.addrfilterPrograms,
		&o.addrfilterMaps,
	)
}

// addrfilterMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadAddrfilterObjects or ebpf.CollectionSpec.LoadAndAssign.
type addrfilterMaps struct {
	CfgMap           *ebpf.Map `ebpf:"cfg_map"`
	LibcRangeMap     *ebpf.Map `ebpf:"libc_range_map"`
	PathWhitelistMap *ebpf.Map `ebpf:"path_whitelist_map"`
	ProfileBuf       *ebpf.Map `ebpf:"profile_buf"`
	ProtectMap       *ebpf.Map `ebpf:"protect_map"`
	StackDbgMap      *ebpf.Map `ebpf:"stack_dbg_map"`
	StatsMap         *ebpf.Map `ebpf:"stats_map"`
	WarnBuf          *ebpf.Map `ebpf:"warn_buf"`
}

func (m *addrfilterMaps) Close() error {
	return _AddrfilterClose(
		m.CfgMap,
		m.LibcRangeMap,
		m.PathWhitelistMap,
		m.ProfileBuf,
		m.ProtectMap,
		m.StackDbgMap,
		m.StatsMap,
		m.WarnBuf,
	)
}

// addrfilterVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadAddrfilterObjects or ebpf.CollectionSpec.LoadAndAssign.
type addrfilterVariables struct {
	UnusedConfigType       *ebpf.Variable `ebpf:"unused_config_type"`
	UnusedKillMode         *ebpf.Variable `ebpf:"unused_kill_mode"`
	UnusedProfileInfo      *ebpf.Variable `ebpf:"unused_profile_info"`
	UnusedStDbg            *ebpf.Variable `ebpf:"unused_st_dbg"`
	UnusedStatType         *ebpf.Variable `ebpf:"unused_stat_type"`
	UnusedSyscallWhitelist *ebpf.Variable `ebpf:"unused_syscall_whitelist"`
	UnusedVmRange          *ebpf.Variable `ebpf:"unused_vm_range"`
}

// addrfilterPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadAddrfilterObjects or ebpf.CollectionSpec.LoadAndAssign.
type addrfilterPrograms struct {
	Addrfilter *ebpf.Program `ebpf:"addrfilter"`
}

func (p *addrfilterPrograms) Close() error {
	return _AddrfilterClose(
		p.Addrfilter,
	)
}

func _AddrfilterClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed addrfilter_x86_bpfel.o
var _AddrfilterBytes []byte
